# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Eemlzey3x2w8m44VHLqgYYylpxRNsvy
"""

import numpy as np
from typing import Dict, Any, Tuple
from pydantic import BaseModel

# OpenEnv Spec: Typed Models
class WarehouseState(BaseModel):
    current_stock: int
    pending_orders: int
    day_of_week: int
    market_demand_forecast: float

class StepResponse(BaseModel):
    state: WarehouseState
    reward: float
    done: bool
    info: Dict[str, Any]

class SmartWarehouseEnv:
    def __init__(self):
        self.max_capacity = 500
        self.holding_cost = 0.1  # Cost per unit per day
        self.stockout_penalty = 5.0  # Penalty per missed sale
        self.reset()

    def reset(self) -> WarehouseState:
        self.stock = 100
        self.day = 0
        self.pending_order_arrival = 0
        return self.state()

    def state(self) -> WarehouseState:
        return WarehouseState(
            current_stock=self.stock,
            pending_orders=self.pending_order_arrival,
            day_of_week=self.day % 7,
            market_demand_forecast=np.random.normal(20, 5)
        )

    def step(self, action: int) -> StepResponse:
        """
        Action: Amount of stock to order (0 to 100)
        """
        # 1. Process incoming orders from previous steps
        self.stock += self.pending_order_arrival

        # 2. Simulate real-world demand
        demand = int(np.random.poisson(25))
        sales = min(self.stock, demand)
        stockout = max(0, demand - self.stock)

        # 3. Apply Action (Supply Chain Lead Time: 2 days)
        self.pending_order_arrival = action

        # 4. Calculate Reward (Profit - Costs)
        # Reward = (Sales * Margin) - (Stock * HoldingCost) - (Stockout * Penalty)
        reward = (sales * 2) - (self.stock * self.holding_cost) - (stockout * self.stockout_penalty)
        # Normalize reward to 0.0 - 1.0 range for OpenEnv graders
        normalized_reward = max(0.0, min(1.0, (reward + 50) / 150))

        self.stock -= sales
        self.day += 1
        done = self.day >= 30  # 30-day simulation

        return StepResponse(
            state=self.state(),
            reward=normalized_reward,
            done=done,
            info={"sales": sales, "stockout": stockout}
        )